#!/bin/sh
# $Id: install-config,v 1.2 2009-11-16 21:52:48 oops Exp $

#
# database client configuration
# set the your database only.
#

# PostgreSQL config
pgsql_client="/usr/bin/psql"

# MySQL config
mysql_client="/usr/bin/mysql"
mysql_config="/usr/bin/mysql_config"

# SQLIte config
sqlite_client="/usr/bin/sqlite"

