#!/bin/sh
clear
echo "########################################################"
echo "# JSBoard Config File Installer v2.0                   #"
echo "# Scripted By JoungKyun Kim < http://www.oops.org >    #"
echo "########################################################"
echo

echo "STEP 1 Language Check"
echo "---------------------"
echo -n "Do you want to use Korean during the installation? [Y/N](default Y) : "
read langs

case "${langs}" in
  N*|n*)
    langs=en ;;
  *)
    langs=ko ;;
esac

if [ "${langs}" = "ko" ]; then
  . ./LANG/ko.conf
else
  . ./LANG/en.conf
fi

# permission configuration
chmod 707 ../../config
chmod 707 -R ../../data
chmod 606 ../../data/*/files/*/*
chmod 606 ../../data/*/*.*
chmod 660 ../../config/global.ph
chmod 606 ../../config/security_data.ph
chmod 660 ../../config/spam_list.txt

echo
echo -e ${ACC_END_MSG}
echo

exit 0
