#!/bin/sh

# 아래의 정보들은 global.ph 의 DB 정보와 동일하게 입력함.
# jsboard 에 접근할 유저이름
DB_USER=

# jsboard 에 접근할 유저 패스워드
DB_PASS=

# jsboard 가 사용할 database 이름
DB_NAME=

# mysql client path
# find /usr -name mysql 로 찾도록 한다.
MPATH=/usr/bin/mysql

TARGET=$(mysql -u${DB_USER} -p${DB_PASS} ${DB_NAME} -e "show tables" | grep  -v "Tables_in_\|userdb")

for i in ${TARGET}
do
  echo "Converting ${i} table ......."
  ${MPATH} -u${DB_USER} -p${DB_PASS} ${DB_NAME} -e "ALTER TABLE ${i} CHANGE moder rname tinytext"
  ${MPATH} -u${DB_USER} -p${DB_PASS} ${DB_NAME} -e "ALTER TABLE ${i} DROP moder"
  ${MPATH} -u${DB_USER} -p${DB_PASS} ${DB_NAME} -e "ALTER TABLE ${i} MODIFY passwd varchar(56)"
done

exit 0
